#!/bin/bash
whisperx renoise_wavs/98.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/99.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/100.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/101.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/102.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/103.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/104.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/105.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/106.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/107.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/108.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/109.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/110.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/111.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/112.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/113.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/114.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/115.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/116.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/117.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/118.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/119.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/120.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/121.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/122.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/123.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/124.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/125.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/126.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/127.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/128.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/129.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/130.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/131.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/132.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/133.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/134.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/135.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/136.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/137.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/138.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/139.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/140.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/141.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/142.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/143.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/144.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/145.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/146.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/147.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/148.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/149.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/150.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/151.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/152.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/153.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/154.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/155.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/156.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/157.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/158.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/159.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/160.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/161.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/162.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/163.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/164.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/165.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/166.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/167.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/168.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/169.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/170.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/171.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/172.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/173.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/174.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/175.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/176.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/177.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/178.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/179.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/180.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/181.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/182.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/183.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/184.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/185.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/186.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/187.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/188.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/189.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/190.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/191.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/192.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/193.wav --compute_type float32 --language vi -o srt
whisperx renoise_wavs/194.wav --compute_type float32 --language vi -o srt
